# Generated by Django 3.0.2 on 2020-02-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='RoomType',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
