# Generated by Django 3.0.2 on 2020-02-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_booking'),
        ('Users', '0005_auto_20200204_1252'),
    ]

    operations = [
    ]
