# Generated by Django 3.0.2 on 2020-02-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_merge_20200204_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='RoomType',
            field=models.CharField(max_length=100),
        ),
    ]
