# Generated by Django 3.0.2 on 2020-02-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20200204_1719'),
        ('Users', '0002_delete_booking'),
    ]

    operations = [
    ]
