# Generated by Django 3.0.2 on 2020-02-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
