# Generated by Django 3.0.2 on 2020-02-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_auto_20200206_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room_cost',
        ),
    ]
