# Generated by Django 3.0.2 on 2020-02-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_delete_room_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Messages', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(),
        ),
    ]
