# Generated by Django 3.0.2 on 2020-02-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_auto_20200207_0853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contactus',
        ),
    ]
