# Generated by Django 3.0.2 on 2020-02-04 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check_In', models.TextField()),
                ('Check_Out', models.TextField()),
                ('Adults', models.IntegerField(null='True')),
                ('Children', models.IntegerField(null='True')),
                ('RoomType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usrs.Rooms')),
            ],
        ),
    ]
