# Generated by Django 3.0.2 on 2020-02-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrs', '0002_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='Date',
            field=models.DateTimeField(default='now', editable=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='NumberOfRooms',
            field=models.IntegerField(default=0),
        ),
    ]
