# Generated by Django 3.0.2 on 2020-02-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrs', '0003_auto_20200206_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='Date',
            new_name='BookedDate',
        ),
    ]
