# Generated by Django 3.0.2 on 2020-02-06 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usrs', '0004_auto_20200206_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='NumberOfRooms',
            new_name='TotalRooms',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='BookedDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
